# Generated by Django 5.0.6 on 2026-01-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0002_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
